meta_product_name: "SupportYourNGO"
meta_title: "SupportYourNGO - Support relevant NGO projects"
meta_description: "Support your ngo is a platform which aims to connect companies and ngos that work on a wide range of social issues. Find your ngos you wich to work with"
meta_image: "meta_image.png"
twitter_account: "@supportyourngo1234"
